# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `date_by_example` gem.
# Please instead update this file by running `bin/tapioca gem date_by_example`.

# THIS IS AN EMPTY RBI FILE.
# see https://github.com/Shopify/tapioca#manually-requiring-parts-of-a-gem
