# frozen_string_literal: true

source "https://rubygems.org"

gemspec
gem "rake", "~> 13.0"
gem "rspec", "~> 3.0"
gem "standard", "~> 1.3"

gem "sorbet", group: :development
gem "sorbet-runtime"
gem "tapioca", require: false, group: :development
